export const GET_ALL_ROOMS_SUCCESS = "GET_ALL_ROOMS_SUCCESS";
export const GET_ALL_ROOMS_FAIL = "GET_ALL_ROOMS_FAIL";

export const GET_ROOM_DETAILS_SUCCESS = "GET_ROOM_DETAILS_SUCCESS";
export const GET_ROOM_DETAILS_FAIL = "GET_ROOM_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
